version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-interview-edge
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'interview-edge'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_USER: 'edge'
      MYSQL_PASSWORD: 'password'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
